### PR TITLE
Added Doctrine DBAL 4 support 

### PR DESCRIPTION
**Pull request by pschombara**
Added support for doctrine/dbal ^4.

Solves #68

### CODE REVIEW

**Review by jochen-jung — APPROVED** [review]

**Comment by VitekSkrip** [comment]
Hi!

I forked your PR and met some problems. For example, in src/ClickHouseSchemaManager.php at line 114 need to convert prep_replace return value to integer because \Doctrine\DBAL\Schema\Column setLength expects ?int value

**Comment by pschombara** [comment]
I fixed the most of the PHPStan errors. 
But one of them I don't know how to solve it for clickhouse.

> 
>  ------ ----------------------------------------------------------------------- 
>   Line   ClickHouseSchemaManager.php                                            
>  ------ ----------------------------------------------------------------------- 
>   82     Method FOD\DBALClickHouse\ClickHouseSchemaManager::listTableIndexes()  
>          should return array<string, Doctrine\DBAL\Schema\Index> but returns    
>          array<int, Doctrine\DBAL\Schema\Index>.

**Comment by asanikovich** [comment]
@pschombara thanks you. I will update github actions, fix phpstan and prepare a new tag.

**Comment by asanikovich** [comment]
@pschombara @VitekSkrip @jochen-jung 
Relase https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v3.0.0 is ready.

**Comment by VitekSkrip** [comment]
Thank u a lot 🥹

**Pull request merged**
