### PR TITLE
Fix issue with database name

### PR DESCRIPTION
**Pull request by kovalevm**

### CODE REVIEW

**Comment by nafigator** [comment]
I think this issue already fixed in [PR#25](https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/25)

**Comment by kovalevm** [comment]
> I think this issue already fixed in [PR#25](https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/25)

Why is it still not in the master?

**Comment by nafigator** [comment]
> > I think this issue already fixed in [PR#25](https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/25)
> 
> Why is it still not in the master?

I hope i'm wrong but looks like this repository is abandoned. Last activity was in [27 Feb](https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/23#pullrequestreview-208739142)

**Comment by MaratCrash** [comment]
Very important fix. Please merge!

**Pull request merged**
