### PR TITLE
Added Doctrine DBAL 3 support

### PR DESCRIPTION
**Pull request by ihortymoshenko**
Hello!

I added support for Doctrine DBAL 3 and leave support only for PHP 8 in this pull request.

I propose to merge these changes to master and make a new major version.

If you have any questions, let's discuss

### CODE REVIEW

**Comment by tarjei** [comment]
Any chance this gets merged?

**Comment by bakl** [comment]
> Any chance this gets merged?

+

**Comment by lionser** [comment]
It is a good chnages, i will wait for marge it. Thanks.

**Comment by russelomua** [comment]
I think better leave compatibility with `php 7` and `dbal ^2.13`. Good if your project is progressive and used a cutting edge technologies, but library must corers to most of users.
p.s. i use an `php 8.1` and want to update project to `dbal ^3`

**Comment by ihortymoshenko** [comment]
@russelomua,

the latest version of this bundle supports PHP 7 and Doctrine DBAL 2, so users should have no issues.

PHP 7 is no longer supported (https://www.php.net/supported-versions.php). There aren't even any security fixes.

We should go ahead and start using PHP 8 and Doctrine DBAL 3

**Comment by russelomua** [comment]
Yep, your totally right, in perfect world it is. But in reality we still have a lot of projects running by php7+ even 5.6 :) My point in if you cud leave support - leave it. Lib owners?

**Comment by ihortymoshenko** [comment]
@russelomua,

you can continue to use this bundle with PHP 7 & Doctrine DBAL 2, this PR is about something else

**Comment by russelomua** [comment]
Maintainers, please. It's time :)

**Comment by asanikovich** [comment]
We will take it in about 2 weeks.

**Comment by russelomua** [comment]
@ihortymoshenko, need to fix README.md because you rename `ArrayStringType` to `ArrayStringableType`
```
  array(string): FOD\DBALClickHouse\Types\ArrayStringType
```

**Comment by russelomua** [comment]
> We will take it in about 2 weeks.

any updates?

**Review by asanikovich — APPROVED** [review]

**Comment by asanikovich** [comment]
We made it. Thank you @ihortymoshenko 

Version https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v2.0.0 ready for you.

**Pull request merged**
